name: auto-deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: npm ci
      - run: npm run deploy