name: auto-deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}