name: auto-deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: npm ci
      - run: npm run deploy