on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./deploy.sh
         ./deploy.sh
      shell: bash
